# -*- coding: utf-8 -*-
"""LabSheet2(AI&ML).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AgiVtnVLS6a98CQpkYZ5EMPyc1P3uLOq

**NUMPY** **ARRAY**
"""

import numpy as np

print(np.__version__)

A1 = np.array([1,2,3,4])
A1

type(A1)

A1.shape

A1.size

A2 = np.array([[1,2,3,4],[5,6,7,8]])
A2

type(A2)

A2.shape

A2.size

A2.ndim

A3 = np.array([[[1,2,3],[4,5,6],[7,8,9,]]])
A3

A32 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[6,5,6]]])
A32

A33 =np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[7,8,9],[6,5,6],[7,8,9]]])
A33

type(A33)

A33.shape

A33.size

A33.ndim

Zeroes Array - an array in which values

ZA = np.zero(shape,dtype)

ZA = np.zeros((3,2))
ZA

Zb = np.zeros((3,2),dtype=int)
Zb

Z3d = np.zeros((2,3,4))
Z3d

Z3d = np.zeros((2,3,4),dtype=int)
Z3d

Z3d = np.ones((2,3,4),dtype=int)
Z3d

"""Full Array"""

FA = np.full(2,6)
FA

FA = np.full(5,6)
FA

FA = np.full((2,3,3),2)
FA

FA = np.full((2,2,2),2,dtype=float)
FA

FA = np.full((2,3,3),'Akash')
FA

FA = np.full((2,3,3),'A',dtype=str)
FA

a = np.array([5,36,4,4])
b = np.array([5,6,7,2])
print(a+b)

"""DATA VISULATION"""

import matplotlib.pyplot as plt

year = [2011,2014,2017,2017,2011,2017,2017,2017,2019,2017,2019,2022,2024,2024,2019,2024,2028,2024,2028,2025]
apples = [3,9,3,6,6,6,9,6,9,6,3,9,3,6,6,6,9,6,4,3]
plt.plot(year,apples)

y=[2003,2004,2005,2006,2007,2008]
ya=[0.34,0.56,0.87,0.78,0.98,0.34]
plt.plot(y,ya)
plt.title('msd')
plt.xlabel('year')
plt.ylabel("yield(tons per hecter)")

