# -*- coding: utf-8 -*-
"""LabSheet1(AI&ML).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/143xWCGDkBPlvylWhSZdXpBl18mS6CsvG
"""

print("Hi")

import keyword
print(keyword.kwlist)
a=len(keyword.kwlist)
print(a)

a = ["a","101","Hi"]
a

b = len(a)
b

a[0]

a[-1]

type(a)

b = list(range(1,21))
b

days = ['monday','tuesday','wednesday','thursday','friday','holiday','holiday']
days

days[2]

days[1:4]

L1 = ["Helo", 1, "Monkey", 2, "Dog", 3, "Donkey"]
New_L1 = L1[0:6:2]
print(New_L1)

days[1:3:5]

a = list(range(1,9))
a

list = [1,2,3,4,5,6,7,8,9]
list

len(list)

max(list)

min(list)

import random
random.shuffle(list)
list

qq =[11,54,6,564,4,65,66,65]
ww =[65,6256,65,6,59,65,6,9,65,96,6,65,6]

qq+ww

del[days[1]]
a

a.append('Hi')
a

c = a.copy()
c

c.extend(days)
 c

s = ('Hi','22','#','%')
s

type(s)

student = {
    'name' : 'Hi',
    'rollno.' : "20211CSD0116",
    'section' : "4CSD-01"
}
student

len(student)

type(student)

y = student.keys()
y

setA = {1,2,1,3,5,4,6,6,4,5,8,5,9,7}
setA

"""numpy arays """